export class CustomersTable {
         public static customers: any = [
           {
             id: 1,
             firstName: 'Tằng',
             lastName: ' A Giáng',
             email: 'giangtang@gmail.com',
             userName: 'agiang',
             gender: 'Nữ',
             status: 0,
             dateOfBbirth: '10/14/1950',
             //   ipAddress: '251.237.126.210',
             type: 1,
             _userId: 1,
             _createdDate: '09/07/2016',
             _updatedDate: '05/31/2013'
           },
           {
             id: 2,
             firstName: 'Trần',
             lastName: 'Giáng Tiên',
             email: 'giangtien@gmail.com',
             userName: 'giangtien',
             gender: 'Nam',
             status: 1,
             dateOfBbirth: '12/31/1998',
             //   ipAddress: '239.176.5.218',
             type: 1,
             _userId: 2,
             _createdDate: '03/18/2014',
             _updatedDate: '08/17/2016'
           },
           {
             id: 3,
             firstName: 'Black',
             lastName: 'Panther',
             email: 'wakanda4ever@gmail.com',
             userName: 'wakanda4ever',
             gender: 'Nữ',
             status: 0,
             dateOfBbirth: '7/3/1957',
             //      ipAddress: '14.80.25.15',
             type: 1,
             _userId: 1,
             _createdDate: '07/03/2015',
             _updatedDate: '01/28/2015'
           },
           {
             id: 4,
             firstName: 'Wonder',
             lastName: 'Woman',
             email: 'strongerthansuperman@gmail.com',
             userName: 'strongerthansuperman',
             gender: 'Nữ',
             status: 2,
             dateOfBbirth: '12/30/1976',
             //    ipAddress: '239.198.18.122',
             type: 0,
             _userId: 2,
             _createdDate: '06/22/2013',
             _updatedDate: '01/31/2011'
           },
           {
             id: 5,
             firstName: 'Dingo',
             lastName: 'Bingo',
             email: 'dingobingo@gmail.com',
             userName: 'dingobingo',
             gender: 'Nữ',
             status: 1,
             dateOfBbirth: '11/23/1996',
             //  ipAddress: '11.19.64.48',
             type: 1,
             _userId: 1,
             _createdDate: '01/30/2018',
             _updatedDate: '05/22/2014'
           },
           {
             id: 6,
             firstName: 'Bran',
             lastName: 'Stark',
             email: 'branstark@gmail.com',
             userName: 'branstark',
             gender: 'Nữ',
             status: 2,
             dateOfBbirth: '4/21/1954',
             // ipAddress: '104.18.128.93',
             type: 1,
             _userId: 1,
             _createdDate: '03/27/2011',
             _updatedDate: '09/02/2015'
           },
           {
             id: 7,
             firstName: 'Dall',
             lastName: 'Stow',
             email: 'dstow6@vistaprint.com',
             userName: 'dstow6',
             gender: 'Nam',
             status: 2,
             dateOfBbirth: '4/14/1998',
             //  ipAddress: '168.199.143.20',
             type: 1,
             _userId: 1,
             _createdDate: '09/05/2011',
             _updatedDate: '06/21/2012'
           },
           {
             id: 8,
             firstName: 'Tô',
             lastName: 'Hũ Tàu',
             email: 'supertofu@gmail.com',
             userName: 'supertofu',
             gender: 'Nam',
             status: 1,
             dateOfBbirth: '8/15/1963',
             //     ipAddress: '204.7.174.42',
             type: 0,
             _userId: 1,
             _createdDate: '09/09/2017',
             _updatedDate: '06/27/2011'
           },
           {
             id: 9,
             firstName: 'Lã',
             lastName: 'Mông Nhụ',
             email: 'lumongnha@gmail.com',
             userName: 'lumongnha',
             gender: 'Nam',
             status: 0,
             dateOfBbirth: '5/20/1997',
             //     ipAddress: '12.229.194.195',
             type: 0,
             _userId: 1,
             _createdDate: '07/16/2011',
             _updatedDate: '05/24/2014'
           },
           {
             id: 10,
             firstName: 'Adham',
             lastName: 'Nguyễn',
             email: 'adamsadler@friendfeed.com',
             userName: 'adamsadler',
             gender: 'Nam',
             status: 1,
             dateOfBbirth: '3/15/1971',
             //    ipAddress: '236.147.173.25',
             type: 0,
             _userId: 2,
             _createdDate: '03/25/2011',
             _updatedDate: '12/13/2015'
           }
         ];
       }
